version: "3"
services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - '${APP_PORT}:80'
    volumes:
      - './:/app'
      - './docker/nginx/conf.d:/etc/nginx/conf.d/'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: apelsin-app
